CREATE TABLE IF NOT EXISTS table_orders (
	"order_id" VARCHAR,
	"product_category" VARCHAR,
	"Status Pesanan" VARCHAR,
	"Alasan Pembatalan" VARCHAR,
    "Opsi Pengiriman" VARCHAR,
	"Waktu Pesanan Dibuat" VARCHAR,
	"Metode Pembayaran" VARCHAR,
    "Jumlah" INT,
	"Returned quantity" FLOAT,
	"Total Diskon" FLOAT,
	"Total Berat" VARCHAR,
    "Ongkos Kirim Dibayar oleh Pembeli" FLOAT,
    "Estimasi Potongan Biaya Pengiriman" FLOAT,
	"Total Pembayaran" VARCHAR,
    "Perkiraan Ongkos Kirim" FLOAT,
	"Kota/Kabupaten" VARCHAR,
	"Provinsi" VARCHAR,
	"source_file" VARCHAR,
    "Waktu Pengiriman Diatur" VARCHAR,
	"Status Pembatalan/ Pengembalian" VARCHAR,
    "No. Resi" VARCHAR,
	"Antar ke counter/ pick-up" VARCHAR,
    "Pesanan Harus Dikirimkan Sebelum (Menghindari keterlambatan)" VARCHAR,
    "Waktu Pembayaran Dilakukan" VARCHAR,
	"SKU Induk" FLOAT,
	"Nomor Referensi SKU" FLOAT,
    "Nama Variasi" VARCHAR,
	"Harga Awal" VARCHAR,
	"Harga Setelah Diskon" VARCHAR,
    "Total Harga Produk" VARCHAR,
	"Diskon Dari Penjual" FLOAT,
	"Diskon Dari Shopee" FLOAT,
    "Berat Produk" VARCHAR,
	"Jumlah Produk di Pesan" FLOAT,
	"Voucher Ditanggung Penjual" FLOAT,
    "Cashback Koin" FLOAT,
	"Voucher Ditanggung Shopee" FLOAT,
	"Paket Diskon" VARCHAR,
    "Paket Diskon (Diskon dari Shopee)" FLOAT,
    "Paket Diskon (Diskon dari Penjual)" FLOAT,
	"Potongan Koin Shopee" FLOAT,
    "Diskon Kartu Kredit" FLOAT,
	"Ongkos Kirim Pengembalian Barang" FLOAT,
    "Catatan dari Pembeli" VARCHAR,
	"Catatan" FLOAT,
	"Username (Pembeli)" VARCHAR,
    "Nama Penerima" VARCHAR,
	"No. Telepon" VARCHAR,
	"Alamat Pengiriman" VARCHAR,
    "Waktu Pesanan Selesai" VARCHAR
);

SELECT * FROM table_orders;

DROP TABLE IF EXISTS table_orders;